### ISSUE TITLE
11/12 よくわからないエラー

### ISSUE THREAD

**Issue by Namiwave** [Namiwave/work#2]
1. herokuをスリープしている状態でbotを動かす
　　以下のようなFlaskのエラー
　　エラーではbusy状態ですよ感があるものの、結構遅れてからちゃんと返事が来る。
　　今までこんなエラーは出たことなかった...どうして？

> 2020-11-12T07:48:04.310568+00:00 heroku[web.1]: Unidling
> 2020-11-12T07:48:04.312826+00:00 heroku[web.1]: State changed from down to starting
> 2020-11-12T07:48:07.987087+00:00 heroku[web.1]: Starting process with command `python main.py`
> 2020-11-12T07:48:10.799638+00:00 app[web.1]:  * Serving Flask app "main" (lazy loading)
> 2020-11-12T07:48:10.799687+00:00 app[web.1]:  * Environment: production
> 2020-11-12T07:48:10.799735+00:00 app[web.1]:    WARNING: This is a development server. Do not use it in a production deployment.
> 2020-11-12T07:48:10.799781+00:00 app[web.1]:    Use a production WSGI server instead.
> 2020-11-12T07:48:10.799805+00:00 app[web.1]:  * Debug mode: off
> 2020-11-12T07:48:10.800987+00:00 app[web.1]:  * Running on http://0.0.0.0:12304/ (Press CTRL+C to quit)
> 2020-11-12T07:48:11.681487+00:00 heroku[web.1]: State changed from starting to up
> 2020-11-12T07:48:13.801711+00:00 heroku[router]: at=info method=POST path="/callback" host=namidogt1.herokuapp.com request_id=62ec84c5-bf5d-401e-9ab6-1377b2c48f05 fwd="147.92.150.197" dyno=web.1 connect=1ms service=443ms status=200 bytes=154 protocol=https
> 2020-11-12T07:48:13.793485+00:00 app[web.1]: 10.69.85.146 - - [12/Nov/2020 07:48:13] "[37mPOST /callback HTTP/1.1[0m" 200 -

2. flexmessageをjson読みこませて送信させる
　　引っ越しメニューのみ実装中。
　　引っ越しのボタンを押すと以下のエラー
　　LINEbot APIでエラー出ている、エラー２か所あるみたいだがエラー文がいまいち読めない
　　json中身の書き方が悪そう。エラー読めれば解決できそう。

> 2020-11-12T07:54:01.059096+00:00 app[web.1]: 
> linebot.exceptions.LineBotApiError: LineBotApiError: 
> status_code=400
> , request_id=fefe99b3-1e08-4ccb-8f71-e7360d3efe37
> , error_response=
>       {"details": [{"message": "May not be empty", "property": "messages[0].altText"}
>     , {"message": "May not be empty", "property": "messages[0].contents"}]
>       , "message": "The request body has 2 error(s)"}
> , headers=
>       {'Server': 'openresty'
>       , 'Content-Type': 'application/json'
>       , 'x-line-request-id': 'fefe99b3-1e08-4ccb-8f71-e7360d3efe37'
>       , 'x-content-type-options': 'nosniff'
>       , 'x-xss-protection': '1; mode=block'
>       , 'x-frame-options': 'DENY'
>       , 'Content-Length': '186'
>       , 'Expires': 'Thu, 12 Nov 2020 07:54:01 GMT'
>       , 'Cache-Control': 'max-age=0, no-cache, no-store'
>       , 'Pragma': 'no-cache'
>       , 'Date': 'Thu, 12 Nov 2020 07:54:01 GMT'
>       , 'Connection': 'close'}

**Comment by KiHirofumi** [comment]
最初のやつはエラーじゃなくてwarningで「無料使ってるからね」ってやつという認識です。

**Comment by KiHirofumi** [comment]
Linebotapi をまだスマホで見た程度できちんと理解してないからなんともですが、
エラーとして言えることはjson にaltText: とcontents: が足りてないって言われている。
それはおそらくtype:"imagemap "であったり、type:"message "であったりしたとこで違うのかな？って推測。
やっぱjson ファイル、もしくは今回flex message 使おうとしてたのに使ってない？とことかが気になってる。

使うなら例えばこう始まるはず。（最初の4行あたりがないから怒られているのでは？）

payload = {
  "type": "flex",
  "altText": "Flex Message",
  "contents": {
    "type": "bubble",
    "hero": {
      "type": "image",
      "url": "https://scdn.line-apps.com/n/channel_devcenter/img/fx/01_1_cafe.png",
      "size": "full",
      "aspectRatio": "20:13",
      "aspectMode": "cover",
      "action": {
        "type": "uri",
        "label": "Line",
        "uri": "https://linecorp.com/"
      }

**Comment by Namiwave** [comment]
@KiHirofumi 
ありがとうございます。後日やってみます。。
やはりjsonの記述ですね…、LINEbotデザイナーで生成されたものをいろんなサイトを参考にしてすこし手を入れたんです。
ちなみに前半がたりない点等というのは、LINEbotDeveloperのマニュアルみたいなサイトを参考にされましたか？

**Comment by KiHirofumi** [comment]
いろんなサイトとここのソース見比べただけです！なので机上チェックだから全然違うかもしれない！
